package codingan;

import static codingan.dashboard.username;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author B4
 */

public class admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public admin(String username) {
        initComponents();
        this.setResizable(false);
        setTitle("admin");
        setNama(username);
        TampilanData();
        waktu();

    }

    private void waktu() {
        Timer t2 = new Timer();
        t2.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                txt_waktu.setText(new SimpleDateFormat("EEEE dd MMMM yyyy hh:mm:ss").format(new java.util.Date()));
            }
        }, 0, 1000);
    }
    
    public void setNama(String user) {
        admin_nama.setText(user);
    }
    
    private void CariData(String Key) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Id Admin");
        model.addColumn("Nama");
        model.addColumn("No Telepon");

        String sql = "SELECT * FROM admin WHERE id_admin LIKE '%" + Key + "%' or nama_admin LIKE '%" + Key + "%'";

        try {
            int no = 1;
            java.sql.Connection conn = (Connection) connection.configDB();
            java.sql.PreparedStatement stm = conn.prepareStatement(sql);
            java.sql.ResultSet rs = stm.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{no++, rs.getString(1), rs.getString(2), rs.getString(3)});
            }
            jTable1.setModel(model);
        } catch (Exception e) {
            e.getMessage();
        }

    }

    private void TampilanData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Id Admin");
        model.addColumn("Nama");
        model.addColumn("No Telepon");

        String sql = "SELECT * FROM admin";

        try {
            int no = 1;
            java.sql.Connection conn = (Connection) connection.configDB();
            java.sql.PreparedStatement stm = conn.prepareStatement(sql);
            java.sql.ResultSet rs = stm.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{no++, rs.getString(1), rs.getString(2), rs.getString(3)});
            }
            jTable1.setModel(model);
        } catch (Exception e) {
            e.getMessage();
        }
    }

    private void Tambahkandata() {
        String sql = "INSERT INTO admin VALUES('" + txt_idAdmin.getText() + "','" + txt_namaAdmin.getText() + "','" + txt_noTlp.getText() + "')";
        System.out.println(sql);
        try {
            java.sql.Connection conn = (Connection) connection.configDB();
            java.sql.PreparedStatement stm = conn.prepareStatement(sql);
            stm.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil di Tambahkan");
            TampilanData();
        } catch (Exception e) {
            e.getMessage();
        }
    }

    private void kosong() {
        txt_idAdmin.enable();
        txt_idAdmin.setText(null);
        txt_namaAdmin.setText(null);
        txt_noTlp.setText(null);
    }

    private void RubahKeExcel(JTable jTable1, File file) {
        try {
            DefaultTableModel Model_Data = (DefaultTableModel) jTable1.getModel();
            FileWriter ObjWriter = new FileWriter(file);
            for (int i = 0; i < Model_Data.getColumnCount(); i++) {
                ObjWriter.write(Model_Data.getColumnName(i) + "\t");
            }

            ObjWriter.write("\n");

            for (int i = 0; i < Model_Data.getRowCount(); i++) {
                for (int j = 0; j < Model_Data.getColumnCount(); j++) {
                    ObjWriter.write(Model_Data.getValueAt(i, j).toString() + "\t");
                }
                ObjWriter.write("\n");
            }

            ObjWriter.close();

        } catch (IOException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_hapus = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_idAdmin = new javax.swing.JTextField();
        txt_namaAdmin = new javax.swing.JTextField();
        txt_noTlp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        btn_dashboard = new javax.swing.JButton();
        btn_data_barang = new javax.swing.JButton();
        btn_supplier = new javax.swing.JButton();
        btn_transaksi_beli = new javax.swing.JButton();
        btn_transaksi_jual = new javax.swing.JButton();
        txt_waktu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btn_hapus.setBackground(new java.awt.Color(255, 153, 102));
        btn_hapus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(204, 0, 204));
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 130, 60));

        btn_edit.setBackground(new java.awt.Color(255, 153, 102));
        btn_edit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(204, 0, 204));
        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 330, 130, 60));

        btn_tambah.setBackground(new java.awt.Color(255, 153, 102));
        btn_tambah.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(204, 0, 204));
        btn_tambah.setText("TAMBAH");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 130, 60));

        btn_clear.setBackground(new java.awt.Color(255, 153, 102));
        btn_clear.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(204, 0, 204));
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 330, 130, 60));

        btn_simpan.setBackground(new java.awt.Color(255, 153, 102));
        btn_simpan.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(204, 0, 204));
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 130, 60));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 204));
        jLabel1.setText("ID Admin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 204));
        jLabel3.setText("Nama Admin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 153));
        jLabel4.setText("No. Telepon");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 30));
        getContentPane().add(txt_idAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 230, 30));
        getContentPane().add(txt_namaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 230, 30));
        getContentPane().add(txt_noTlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 230, 30));

        jTable1.setBackground(new java.awt.Color(255, 153, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 1180, 290));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 204));
        jLabel5.setText("CARI DATA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, 30));

        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });
        getContentPane().add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 660, 30));

        btn_dashboard.setBorder(null);
        btn_dashboard.setContentAreaFilled(false);
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, 150, 60));

        btn_data_barang.setBorder(null);
        btn_data_barang.setContentAreaFilled(false);
        btn_data_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_data_barangActionPerformed(evt);
            }
        });
        getContentPane().add(btn_data_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 75, 230, 60));

        btn_supplier.setBorder(null);
        btn_supplier.setContentAreaFilled(false);
        btn_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supplierActionPerformed(evt);
            }
        });
        getContentPane().add(btn_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 75, 170, 60));

        btn_transaksi_beli.setBorder(null);
        btn_transaksi_beli.setContentAreaFilled(false);
        btn_transaksi_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksi_beliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_transaksi_beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 75, 230, 60));

        btn_transaksi_jual.setBorder(null);
        btn_transaksi_jual.setContentAreaFilled(false);
        btn_transaksi_jual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksi_jualActionPerformed(evt);
            }
        });
        getContentPane().add(btn_transaksi_jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 75, 240, 60));

        txt_waktu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_waktu.setForeground(new java.awt.Color(204, 0, 204));
        txt_waktu.setText("Tanggal");
        getContentPane().add(txt_waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, 30));

        admin_nama.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        admin_nama.setForeground(new java.awt.Color(204, 0, 204));
        admin_nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin_nama.setText("Username");
        getContentPane().add(admin_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Admin1.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        Tambahkandata();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String ID_Admin = jTable1.getValueAt(baris, 1).toString();
        txt_idAdmin.setText(ID_Admin);
        txt_idAdmin.disable();
        if (jTable1.getValueAt(baris, 1) == null) {
            txt_idAdmin.setText("");
        } else {
            txt_idAdmin.setText(jTable1.getValueAt(baris, 1).toString());
        }
        if (jTable1.getValueAt(baris, 2) == null) {
            txt_namaAdmin.setText("");
        } else {
            txt_namaAdmin.setText(jTable1.getValueAt(baris, 2).toString());
        }
        if (jTable1.getValueAt(baris, 3) == null) {
            txt_noTlp.setText("");
        } else {
            txt_noTlp.setText(jTable1.getValueAt(baris, 3).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        String key = txt_cari.getText();

        if (key != "") {
            CariData(key);

        } else {
            TampilanData();
        }
    }//GEN-LAST:event_txt_cariKeyReleased

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        File pathDefault = new File("C:\\Users\\LENOVO\\Downloads");
        if (!pathDefault.exists()) {
            pathDefault.mkdir();
        } else if (pathDefault.exists()) {
            java.util.Date tgl = new java.util.Date();
            File fp = new File("C:\\Users\\LENOVO\\Downloads\\excel" + tgl.getTime() + ".xls");
            JOptionPane.showMessageDialog(null, "DATA SUKSES DI SIMPAN");
            RubahKeExcel(jTable1, fp);
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        String sql = "DELETE FROM admin WHERE id_admin = '" + txt_idAdmin.getText() + "'";
        try {
            java.sql.Connection conn = (Connection) connection.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil di Hapus");
            TampilanData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "EROR \n" + e.getMessage());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        String sql = "UPDATE admin Set id_admin = '" + txt_idAdmin.getText() + "',nama_admin = '" + txt_namaAdmin.getText() + "',no_tlp = '" + txt_noTlp.getText()
                + "' WHERE id_admin = '" + txt_idAdmin.getText() + "'";
        try {
            java.sql.Connection conn = (Connection) connection.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Berhasil di edit");
            TampilanData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "EROR \n" + e.getMessage());
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        kosong();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        this.setVisible(false);
        new dashboard(admin_nama.getText()).setVisible(true);
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_data_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_data_barangActionPerformed
        this.setVisible(false);
        new data_barang(admin_nama.getText()).setVisible(true);
    }//GEN-LAST:event_btn_data_barangActionPerformed

    private void btn_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supplierActionPerformed
        this.setVisible(false);
        new supplier(admin_nama.getText()).setVisible(true);
    }//GEN-LAST:event_btn_supplierActionPerformed

    private void btn_transaksi_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksi_beliActionPerformed
        this.setVisible(false);
        new transaksi_beli(admin_nama.getText()).setVisible(true);
    }//GEN-LAST:event_btn_transaksi_beliActionPerformed

    private void btn_transaksi_jualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksi_jualActionPerformed
        this.setVisible(false);
        new transaksi_jual(admin_nama.getText()).setVisible(true);
    }//GEN-LAST:event_btn_transaksi_jualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin(admin_nama.getText()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JLabel admin_nama = new javax.swing.JLabel();
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_data_barang;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_supplier;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_transaksi_beli;
    private javax.swing.JButton btn_transaksi_jual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_idAdmin;
    private javax.swing.JTextField txt_namaAdmin;
    private javax.swing.JTextField txt_noTlp;
    private javax.swing.JLabel txt_waktu;
    // End of variables declaration//GEN-END:variables

}
