package codingan;

import static codingan.dashboard.username;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author B4
 */

public class supplier extends javax.swing.JFrame {

    /**
     * Creates new form supplier
     */
    
    public supplier(String username) {
        initComponents();
        this.setResizable(false);
        setTitle("Supplier");
        setNama(username);
        TampilanData();
        waktu();
    }

    public void setNama(String user) {
        supplier_nama.setText(user);
    }
    
    private void waktu() {
        Timer t2 = new Timer();
        t2.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                txt_waktu.setText(new SimpleDateFormat("EEEE dd MMMM yyyy hh:mm:ss").format(new java.util.Date()));
            }
        }, 0, 1000);
    }
    private void CariData(String Key){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Id Supplier");
        model.addColumn("Nama");
        model.addColumn("No Telepon");

        
        String sql = "SELECT * FROM supplier WHERE id_supp LIKE '%"+Key+"%' or nama_supp LIKE '%"+Key+"%'";
        
        try{
           int no = 1;
           java.sql.Connection conn = (Connection)connection.configDB();
           java.sql.PreparedStatement stm = conn.prepareStatement(sql);
           java.sql.ResultSet rs = stm.executeQuery();
           while(rs.next()){
               model.addRow(new Object[]{no++, rs.getString(1),rs.getString(2),rs.getString(3)});
           }
           jTable1.setModel(model);
       }
       catch(Exception e){
           e.getMessage();
       }   
        
    }
    
    private void TampilanData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Id Supplier");
        model.addColumn("Nama Supplier");
        model.addColumn("No. Telepon");
       //Menampilkan data database ke dalam table 
       try {
            int no = 1;
            String sql = "SELECT * FROM supplier";
            java.sql.Connection conn = (Connection) connection.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{
                    no++,
                    res.getString(1), 
                    res.getString(2), 
                    res.getString(3)                  
                });   
            }
            jTable1.setModel(model);
        } catch (Exception e) {            
        }
    }
     private void kosong() {
        txt_idSupplier.enable();
        txt_idSupplier.setText(null);
        txt_namaSupplier.setText(null);
        txt_noTlp.setText(null);
    }
    
      private void RubahKeExcel(JTable jTable1, File file) {
          try {
            DefaultTableModel Model_Data = (DefaultTableModel) jTable1.getModel();
            FileWriter ObjWriter = new FileWriter(file);
            for (int i = 0; i < Model_Data.getColumnCount(); i++) {
                ObjWriter.write(Model_Data.getColumnName(i) + "\t");
            }

            ObjWriter.write("\n");

            for (int i = 0; i < Model_Data.getRowCount(); i++) {
                for (int j = 0; j < Model_Data.getColumnCount(); j++) {
                    ObjWriter.write(Model_Data.getValueAt(i, j).toString() + "\t");
                }
                ObjWriter.write("\n");
            }

            ObjWriter.close();

        } catch (IOException e) {
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_edit = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_idSupplier = new javax.swing.JTextField();
        txt_namaSupplier = new javax.swing.JTextField();
        txt_noTlp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        btn_dashboard = new javax.swing.JButton();
        btn_data_barang = new javax.swing.JButton();
        btn_admin = new javax.swing.JButton();
        btn_transaksi_beli = new javax.swing.JButton();
        btn_transaksi_jual = new javax.swing.JButton();
        txt_waktu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(255, 153, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 1200, 290));

        btn_edit.setBackground(new java.awt.Color(255, 153, 102));
        btn_edit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(204, 0, 153));
        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel2.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 140, 60));

        btn_tambah.setBackground(new java.awt.Color(255, 153, 102));
        btn_tambah.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(204, 0, 153));
        btn_tambah.setText("TAMBAH");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jPanel2.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 140, 60));

        btn_hapus.setBackground(new java.awt.Color(255, 153, 102));
        btn_hapus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(204, 0, 153));
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel2.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 140, 60));

        btn_clear.setBackground(new java.awt.Color(255, 153, 102));
        btn_clear.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(204, 0, 153));
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel2.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 330, 140, 60));

        btn_simpan.setBackground(new java.awt.Color(255, 153, 102));
        btn_simpan.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(204, 0, 153));
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel2.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 330, 140, 60));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 153));
        jLabel1.setText("ID Supplier");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 153));
        jLabel3.setText("Nama Supplier");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 30));
        jPanel2.add(txt_idSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 200, 30));
        jPanel2.add(txt_namaSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 200, 30));
        jPanel2.add(txt_noTlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 200, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 153));
        jLabel4.setText("No. Telepon");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 120, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 204));
        jLabel5.setText("Cari Data");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 90, 50));

        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });
        jPanel2.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 680, 30));

        btn_dashboard.setBorder(null);
        btn_dashboard.setContentAreaFilled(false);
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });
        jPanel2.add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, 70));

        btn_data_barang.setBorder(null);
        btn_data_barang.setContentAreaFilled(false);
        btn_data_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_data_barangActionPerformed(evt);
            }
        });
        jPanel2.add(btn_data_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 220, 70));

        btn_admin.setBorder(null);
        btn_admin.setContentAreaFilled(false);
        btn_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminActionPerformed(evt);
            }
        });
        jPanel2.add(btn_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 150, 70));

        btn_transaksi_beli.setBorder(null);
        btn_transaksi_beli.setContentAreaFilled(false);
        btn_transaksi_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksi_beliActionPerformed(evt);
            }
        });
        jPanel2.add(btn_transaksi_beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 240, 70));

        btn_transaksi_jual.setBorder(null);
        btn_transaksi_jual.setContentAreaFilled(false);
        btn_transaksi_jual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksi_jualActionPerformed(evt);
            }
        });
        jPanel2.add(btn_transaksi_jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 70, 240, 70));

        txt_waktu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_waktu.setForeground(new java.awt.Color(204, 0, 204));
        txt_waktu.setText("Tanggal");
        jPanel2.add(txt_waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, 20));

        supplier_nama.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        supplier_nama.setForeground(new java.awt.Color(204, 0, 204));
        supplier_nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        supplier_nama.setText("Username");
        jPanel2.add(supplier_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Supplier1.jpeg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
    String key = txt_cari.getText();
         
    if(key!=""){
     CariData(key);
    
    }else{
     TampilanData();
    }
    }//GEN-LAST:event_txt_cariKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      int baris = jTable1.rowAtPoint(evt.getPoint());
      String ID_Supplier = jTable1.getValueAt(baris, 1).toString();
      txt_idSupplier.setText(ID_Supplier);
      txt_idSupplier.disable();
      if(jTable1.getValueAt(baris, 1)==null){
            txt_idSupplier.setText("");
        } else {
            txt_idSupplier.setText(jTable1.getValueAt(baris, 1).toString());
        }
        if(jTable1.getValueAt(baris, 2)==null){
            txt_namaSupplier.setText("");
        } else {
            txt_namaSupplier.setText(jTable1.getValueAt(baris, 2).toString());
        }
          if(jTable1.getValueAt(baris, 3)==null){
            txt_noTlp.setText("");
        } else {
            txt_noTlp.setText(jTable1.getValueAt(baris, 3).toString());
          } 
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
         try {
            String sql = "INSERT INTO supplier VALUES ('" + txt_idSupplier.getText() +  "','" + txt_namaSupplier.getText()
                     + "','" + txt_noTlp.getText() + "')";
            java.sql.Connection conn = (Connection) connection.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Tambahkan");          
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        TampilanData();
        kosong();  
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        String sql = "UPDATE supplier Set id_supp = '"+txt_idSupplier.getText()+"',nama_supp = '"+txt_namaSupplier.getText()+"',no_tlp = '"+txt_noTlp.getText()
                + "' WHERE id_supp = '" + txt_idSupplier.getText()+"'";
        try{
           java.sql.Connection conn=(Connection)connection.configDB();
           java.sql.PreparedStatement pst = conn.prepareStatement(sql);
           pst.execute();
           JOptionPane.showMessageDialog(this, "Data Berhasil di edit");
           TampilanData();
       } catch (Exception e){
           JOptionPane.showMessageDialog(null, "EROR \n"+e.getMessage());   
       }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
       String sql= "DELETE FROM supplier WHERE id_supp = '"+txt_idSupplier.getText()+"'";
       try{
           java.sql.Connection conn=(Connection)connection.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
           pst.execute();
           JOptionPane.showMessageDialog(this, "Data Berhasil di Hapus");
           TampilanData();
       } catch (Exception e){
           JOptionPane.showMessageDialog(null, "EROR \n"+e.getMessage());   
       }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
       kosong();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        File pathDefault = new  File("C:\\Users\\LENOVO\\Downloads");
          if(!pathDefault.exists()) {
              pathDefault.mkdir();
          }else if(pathDefault.exists()) {
              java.util.Date tgl = new java.util.Date();
              File fp = new File("C:\\Users\\LENOVO\\Downloads\\excel"+ tgl.getTime()+ ".xls");
              JOptionPane.showMessageDialog(null, "DATA SUKSES DI SIMPAN");
              RubahKeExcel(jTable1, fp);
          }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        this.setVisible(false);
        new dashboard(username.getText()).setVisible(true);
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_data_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_data_barangActionPerformed
        this.setVisible(false);
        new data_barang(username.getText()).setVisible(true);
    }//GEN-LAST:event_btn_data_barangActionPerformed

    private void btn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminActionPerformed
        this.setVisible(false);
        new admin(username.getText()).setVisible(true);
    }//GEN-LAST:event_btn_adminActionPerformed

    private void btn_transaksi_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksi_beliActionPerformed
        this.setVisible(false);
        new transaksi_beli(username.getText()).setVisible(true);
    }//GEN-LAST:event_btn_transaksi_beliActionPerformed

    private void btn_transaksi_jualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksi_jualActionPerformed
       this.setVisible(false);
        new transaksi_jual(username.getText()).setVisible(true);
    }//GEN-LAST:event_btn_transaksi_jualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supplier(supplier_nama.getText()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_admin;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_data_barang;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_transaksi_beli;
    private javax.swing.JButton btn_transaksi_jual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public static final javax.swing.JLabel supplier_nama = new javax.swing.JLabel();
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_idSupplier;
    private javax.swing.JTextField txt_namaSupplier;
    private javax.swing.JTextField txt_noTlp;
    private javax.swing.JLabel txt_waktu;
    // End of variables declaration//GEN-END:variables

}
